{% if serviceSpecificSecret %}
---
apiVersion: v1
kind: Secret
metadata:
  name: env-{{ datadog_name }}
  namespace: {{ namespace }}
type: Opaque
data:
{% for k, v  in secrets.items() %}
  {{ k }}: {{ v | base64encode }}{{ '\n' }}{% endfor %}

{% endif %}
---
{% if label is not defined %}{% set label = 'app' %}{% endif %}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app: {{ name }}
    tags.datadoghq.com/service: {{ datadog_name }}
    tags.datadoghq.com/version: "{{ release }}"
{% if labels is defined %}{{ labels | to_yaml(indent=4) }}{% endif %}
spec:
  revisionHistoryLimit: {{ historyLimit or 1}}
  selector:
    matchLabels:
      app: {{ name }}
  template:
    metadata:
      labels:
        app: {{ name }}
        env: {{ hash }}
        tags.datadoghq.com/service: {{ datadog_name }}
        tags.datadoghq.com/version: "{{ release }}"
    spec:
    {% if affinity %}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: 
                  - {{ name }}
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      {% endif %}
      securityContext:
        fsGroup: {{ uid if uid is not none else 1000 }}
        runAsUser: {{ uid if uid is not none else 1000 }}
      containers:
      - name: {{ name }}
        image: {{ image }}
        imagePullPolicy: Always
        {% if command is defined%}
        command: {{ command }}
        {%endif%}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        {% if environment is defined %}
        {% for env in environment %}
        - name: {{ env.name }}
          value: {{ env.value }}
        {% endfor %}{% endif %}
        envFrom:
        - secretRef:
            name: env-{{ app }}
        {% if secrets %}
        - secretRef:
            name: env-{{ datadog_name }}
            optional: {{ not serviceSpecificSecret }}
        {% endif %}
        volumeMounts:
        - name: apmsocketpath
          mountPath: /var/run/datadog
        {% if volumes is defined %}
        {% for volume in volumes %}
        - name: {{ volume.name }}
          mountPath: {{ volume.path }}
          {% if volume.type == 'secret' %}
          readOnly: true
          {% endif %}
        {% endfor %}{% endif %}
        {% if resources is defined %}
        resources:
{{resources | to_yaml}}{% endif %}
        {% if livenessProbe is defined %}
        livenessProbe:
{{ livenessProbe | to_yaml }}{% endif %}
        {% if readinessProbe is defined %}
        readinessProbe:
{{ readinessProbe | to_yaml }}{% endif %}
        {% if lifecycle is defined %}
        lifecycle:
{{ lifecycle | to_yaml}}{% endif %}
      {% if terminationGracePeriodSeconds is defined %}terminationGracePeriodSeconds: {{ terminationGracePeriodSeconds }}
      {% endif %}
      volumes:
      - name: apmsocketpath
        hostPath:
          path: /var/run/datadog/
      {% if volumes is defined %}{% for volume in volumes %}
      - name: {{ volume.name }}
        {{ volume.type }}:
{{ volume.args | to_yaml }}{% endfor %}{% endif %}
{%- if ports is defined %}
---
kind: Service
apiVersion: v1
metadata:
  name: {{name}}
  namespace: {{ namespace }}
  labels:
    app: {{name}}
spec:
  selector:
    app: {{name}}
  ports:
  {% for port in ports %}
  - name: {{ port.name }}
    protocol: TCP
    port: {{ port.source }}
    targetPort: {{ port.target }}
  {%endfor%}
{% endif %}