---
apiVersion: v1
kind: Secret
metadata:
  name: env-{{ app }}
  namespace: {{ namespace }}
type: Opaque
data:
{% for k, v  in secrets.items() %}
  {{ k }}: {{ v | base64encode }}{{ '\n' }}{% endfor %}