common: &common
  name: ipfs
  serviceSpecificSecret: False
  affinity: False
  ports:
    - name: ipfs
      source: 5001
      target: 5001
  image: ipfs/go-ipfs:v0.4.23
  resources:
    limits:
      cpu: 250m
      memory: 1G
    requests:
      cpu: 250m
      memory: 1G

simulation:
  <<: *common
  namespace: simulation